services:
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    image: poker:poker
    build:
      context: .
      target: final
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      API_PORT: 8080
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  db:
    driver: local
