-- Your SQL goes here
CREATE TABLE PLAYER (
	ID SERIAL NOT NULL PRIMARY KEY,
	NAME VARCHAR(25) NOT NULL UNIQUE,
	SCORE INTEGER NOT NULL,
	IMAGE_URL VARCHAR(1000) NOT NULL
);

CREATE TABLE SOUL (
        ID SERIAL NOT NULL PRIMARY KEY,
	OWNER INTEGER REFERENCES PLAYER(ID) NOT NULL,
	NAME VARCHAR(25) REFERENCES PLAYER(NAME) NOT NULL
);

CREATE TABLE ADMIN (
	ID SERIAL NOT NULL PRIMARY KEY,
	USERNAME VARCHAR(25) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL
);

INSERT INTO ADMIN VALUES (1, 'Grandkahuna43325', '$argon2id$v=19$m=307200,t=1,p=4$l3v4s506a/YL8DXkg62NGw$cucZSJuf4GC5hiRYOa9MhHQ9dpOJ1x1321t8EwJjY58');
